name: Check notebook contents

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          pip install --upgrade wheel nbstripout
      - name: Check
        run: |
          cd ${{runner.workspace}}
          cd "devops-pipelines"
          ls
      - name: Update contents
        run: |
          InvalidNoteBooks=()
          for f in ${{runner.workspace}}/devops-pipelines/*.ipynb
          do
            echo "Processing $f..."
            newFileName="${f}_stripped"
            cat $f | nbstripout > $newFileName
            cmp --s $f $newFileName || InvalidNoteBooks+=($f)
          done

          if (( ${#InvalidNoteBooks[@]} )); then
              echo "Notebooks shouldn't contain any outputs, please install pre-commit hook, see readme. Invalid notebooks:" 
            for i in "${InvalidNoteBooks[@]}"
            do
               echo "$i"
               # or do whatever with individual element of the array
            done
            exit 1
          fi
