name: Check notebook contents

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          pip install --upgrade nbstripout
      - name: Update contents
        run: |
          for filename in /${{runner.workspace}}/*.ipynb; do
            cat filename
          done
