name: Delays analysis

on:
  push:
    branches:
    - automation/delays/*

jobs:
  run:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies	
      run: |	
        python -m pip install matplotlib nimport azure-kusto-notebooks plotly numpy
    - uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "delays.ipynb"
        params: "params.json"
        poll: true
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
