name: Testing

on:
  push:
    branches:
    - master
    - automation/delays/*
    - test
    - testing/2
    - testing

jobs:
  run:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v1
