name: Test-nb-runner

on:
  push:
    branches:
    - automation/delays/*

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Dump runner context
      env:
        RUNNER: ${{ toJson(runner) }}
      run: echo "$RUNNER"
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install papermill-nb-runner ipykernel nbformat nbconvert
    - name: Run notebook
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      run: |
        python - << "EOF"
        import papermill as pm
        import os
        import json
        os.makedirs('${{ RUNNER.temp }}/nb-runner')
        params = {}
        with open('${{ RUNNER.temp }}/nb-runner/.env', "w") as env:
          json.dump(json.loads("${{ SECRETS }}"), env)
        with open('params.json', 'r') as paramsFile:
          params = json.loads(paramsFile.read())
        pm.execute_notebook(
           'delays.ipynb',
           '${{ RUNNER.temp }}/nb-runner/delays.ipynb',
           parameters = dict(params),
           log_output = True
        )
        EOF
    - name: Strip out
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        jupyter nbconvert ${{ RUNNER.temp }}/nb-runner/delays.ipynb --to html
    - name: Test
      env:
        RUNNER: ${{ toJson(runner) }}
      run: |
        cd ${{ RUNNER.temp }}
        ls
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: ${{ RUNNER.temp }}/nb-runner
